#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom AnnotationDbi mapIds
#' @importFrom chevreuldata human_gene_transcript_sce
#' @importFrom chevreulProcess build_bigwig_db
#' @importFrom chevreulProcess get_colData
#' @importFrom chevreulProcess get_feature_types
#' @importFrom chevreulProcess get_features
#' @importFrom chevreulProcess get_object_metadata
#' @importFrom chevreulProcess get_variable_features
#' @importFrom chevreulProcess list_plot_types
#' @importFrom chevreulProcess query_experiment
#' @importFrom chevreulProcess retrieve_experiment
#' @importFrom chevreulProcess run_object_de
#' @importFrom chevreulProcess set_colData
#' @importFrom chevreulProcess set_feature_type
#' @importFrom circlize colorRamp2
#' @importFrom cluster agnes
#' @importFrom ComplexHeatmap draw
#' @importFrom ComplexHeatmap Heatmap
#' @importFrom ComplexHeatmap HeatmapAnnotation
#' @importFrom DBI dbAppendTable
#' @importFrom DBI dbConnect
#' @importFrom DBI dbDisconnect
#' @importFrom DBI dbReadTable
#' @importFrom DBI dbWriteTable
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr one_of
#' @importFrom dplyr pull
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarize
#' @importFrom dplyr top_n
#' @importFrom DT datatable
#' @importFrom DT DTOutput
#' @importFrom DT formatStyle
#' @importFrom DT renderDT
#' @importFrom EnsDb.Hsapiens.v86 EnsDb.Hsapiens.v86
#' @importFrom EnsDb.Mmusculus.v79 EnsDb.Mmusculus.v79
#' @importFrom forcats fct_na_value_to_level
#' @importFrom fs dir_ls
#' @importFrom fs path
#' @importFrom fs path_abs
#' @importFrom fs path_dir
#' @importFrom fs path_expand
#' @importFrom fs path_ext_remove
#' @importFrom fs path_ext_set
#' @importFrom fs path_file
#' @importFrom future plan
#' @importFrom glue glue
#' @importFrom grid unit
#' @importFrom methods is
#' @importFrom methods slot
#' @importFrom methods slot<-
#' @importFrom patchwork wrap_plots
#' @importFrom plotly config
#' @importFrom plotly event_data
#' @importFrom plotly ggplotly
#' @importFrom plotly highlight
#' @importFrom plotly layout
#' @importFrom plotly partial_bundle
#' @importFrom plotly style
#' @importFrom plotly toWebGL
#' @importFrom purrr flatten_chr
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_if
#' @importFrom purrr map_int
#' @importFrom purrr map_lgl
#' @importFrom purrr map2
#' @importFrom purrr pmap
#' @importFrom purrr reduce
#' @importFrom purrr set_names
#' @importFrom rappdirs user_cache_dir
#' @importFrom RSQLite SQLite
#' @importFrom S4Vectors metadata
#' @importFrom scales hue_pal
#' @importFrom scales pseudo_log_trans
#' @importFrom scales rescale
#' @importFrom scater plotDots
#' @importFrom scater plotExpression
#' @importFrom scater plotReducedDim
#' @importFrom scran getTopHVGs
#' @importFrom stats as.dendrogram
#' @importFrom stats dist
#' @importFrom stats hclust
#' @importFrom stats reorder
#' @importFrom stats runif
#' @importFrom stats setNames
#' @importFrom stringr str_detect
#' @importFrom stringr str_remove
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_subset
#' @importFrom stringr str_to_title
#' @importFrom tibble column_to_rownames
#' @importFrom tibble deframe
#' @importFrom tibble enframe
#' @importFrom tibble rownames_to_column
#' @importFrom tidyr drop_na
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr unite
#' @importFrom utils capture.output
#' @importFrom utils data
#' @importFrom utils head
#' @importFrom utils packageVersion
#' @importFrom utils sessionInfo
#' @importFrom wiggleplotr plotCoverageFromEnsembldb
## usethis namespace: end
#' @import ggplot2
#' @import SingleCellExperiment
#' @import SummarizedExperiment
#' @import dplyr
#' @import stringr
#' @import tidyr
NULL